MIRe2/MIRe/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('MIReApp.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

MIRe2/MIReApp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('perfiles/', views.perfiles, name='perfiles'),
    path('deshabilitar_usuario/<int:id>/', views.deshabilitar_usuario, name='deshabilitar_usuario'),
    path('registrar_admin/', views.registrar_admin, name='registrar_admin'),
    path('registrar_owner/', views.registrar_owner, name='registrar_owner'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    path('error', views.error, name='error'),
    path('nosotros', views.nosotros, name='nosotros'),
    path('tipos', views.tipos, name = "tipos"),
    path('get_chart', views.get_chart, name='get_chart'),
    path('valores', views.valores, name = "valores"),
    path('medidas', views.medidas, name = "medidas"),
    path('listar_metricas', views.listar_metricas, name = "listar_metricas"),
    path('crear_excel', views.crear_excel, name="crear_excel"),
    path('instancias', views.instancias, name = "instancias"),
    path('programas',views.programas, name='programas'),
    path('programas/crear',views.crear_programa, name='crear_programa'),
    path('programas/eliminar/<int:id>', views.eliminar_programas, name='eliminar_programas'),
    path('programas/editar/<int:id>', views.editar_programas, name='editar_programas'),
    path('indicadores',views.indicadores, name='indicadores'),
    path('indicadores/crear', views.crear_indicadores, name='crear_indicador'),
    path('indicadores/eliminar/<int:id>', views.eliminar_indicador, name='eliminar_indicador'),
    path('indicadores/editar/<int:id>', views.editar_indicadores, name='editar_indicador'),
    path('metricas', views.metricas, name='metricas'),
    path('metricas/crear', views.crear_metricas, name='crear'),
    path('metricas/editar/<int:id>', views.editar_metricas, name='editar'),
    path('metricas/eliminar/<int:id>', views.eliminar_metricas, name='eliminar'),
    path('historial-metrica/<int:metrica_id>/', views.historial_metrica, name='historial_metrica'),
    path('eliminar_historial_metrica/<int:historial_id>/', views.eliminar_historial_metrica, name='eliminar_historial_metrica'),
]

MIRe2/MIReApp/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.db import models

 
FRECUENCIAS = (('Cuatrienal','Cuatrienal'),('Bianual','Bianual'), ('Anual', 'Anual'), ('Semestral','Semestral'), ('Mensual','Mensual'))
FORMULAS = (('Inversion promedio','Inversion promedio'), ('Tasa de variacion','Tasa de variacion'), ('Porcentaje','Porcentaje'))
MESES = (('Enero','Enero'),('Febrero','Febrero'),('Marzo','Marzo'),('Abril','Abril'),('Mayo','Mayo'),('Junio','Junio'),('Julio','Julio'),('Agosto','Agosto'),('Septiembre','Septiembre'),('Octubre','Octubre'),('Noviembre','Noviembre'),('Diciembre','Diciembre'))
SEMESTRES = (('Enero-Junio', 'Enero-Junio'),('Julio-Diciembre', 'Julio-Diciembre'))
AREAS = (('Ingeniería en Sistemas de Información', 'Ingeniería en Sistemas de Información'),('Ingeniería Química', 'Ingeniería Química'),('Ingeniería Electromecánica', 'Ingeniería Electromecánica'),('Materias Básicas', 'Materias Básicas'))

def validate_year(value):
    current_year = timezone.now().year
    if value < 2010 or value > current_year:
        raise ValidationError(f"El año debe estar en el rango de 2010 a {current_year}.")

class Metrica(models.Model):
    id = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=100, 
                              verbose_name='Título',
                              unique= True,
                              validators= [
                                  RegexValidator(regex= r'^[a-zA-Z\s]*$',
                                                 message="El nombre no puede contener caracteres especiales.",
                                                 code='invalid_nombre')
                              ])
    descripcion = models.TextField(max_length=100, verbose_name='Descripción', blank=True, null=True)  #blank=True y null=True permiten que el campo se envie vacio 
    unidad_medida = models.CharField(max_length=100, 
                                        verbose_name='Unidad de Medida',
                                        validators= [
                                            RegexValidator(regex= r'^[a-zA-Z\s]*$',
                                                            message="La unidad de medida no puede contener caracteres especiales",
                                                            code='invalid_nombre')
                                        ])
    frecuencia = models.CharField(max_length=10, choices=FRECUENCIAS)
    valor = models.IntegerField(verbose_name='Valor', validators=[MinValueValidator(0, message="El valor no puede ser negativo")], default=0)
    year = models.PositiveIntegerField(verbose_name='Ingrese año:', validators=[validate_year])
    month = models.CharField(max_length=10, verbose_name='Ingrese mes:', choices=MESES, blank=True, null=True)
    semestral = models.CharField(max_length=15, verbose_name='Ingrese semestre:', choices=SEMESTRES, blank=True, null=True,)
    year2 = models.PositiveIntegerField(blank=True, null=True, verbose_name='Segundo año')

    def __str__(self):
        fila = self.titulo
        return fila
    
class Indicador(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100, 
                              verbose_name='Nombre',
                              unique= True,
                              validators= [
                                  RegexValidator(regex= r'^[a-zA-Z\s]*$',
                                                 message="El nombre no puede contener caracteres especiales.",
                                                 code='invalid_nombre')
                              ])
    descripcion = models.CharField(max_length=100, verbose_name='Descripción', blank=True, null=True) 
    ambito = models.ForeignKey('Ambito', on_delete=models.CASCADE)
    tipo = models.ForeignKey('Tipo', on_delete=models.CASCADE)
    programa = models.ForeignKey('Programa', on_delete=models.SET_NULL, null=True, blank=True)
    objetivo = models.ForeignKey('Objetivos', on_delete=models.CASCADE, blank=True, null=True)
    frecuencia = models.CharField(verbose_name='Frecuencia de medición',max_length=10, choices=FRECUENCIAS)
    formula = models.CharField(max_length=20, choices= FORMULAS,verbose_name='Formula', blank=True) 
    numerador = models.ForeignKey('Metrica', related_name='Numerador', on_delete=models.CASCADE, blank=True, null=True)
    denominador = models.ForeignKey('Metrica', related_name='Denominador', on_delete=models.CASCADE, blank=True, null=True) 
    numerador_periodo = models.ForeignKey('HistorialMetrica', related_name='Instancia_Numerador', on_delete=models.CASCADE, blank=True, null=True)
    denominador_periodo = models.ForeignKey('HistorialMetrica', related_name='Instancia_Denominador', on_delete=models.CASCADE, blank=True, null=True)
    numerador_medida = models.CharField(max_length=100, verbose_name='', blank=True, null=True) 
    denominador_medida = models.CharField(max_length=100, verbose_name='', blank=True, null=True) 
    numerador_valor = models.PositiveIntegerField(verbose_name='', blank=True, null=True) 
    denominador_valor = models.PositiveIntegerField(verbose_name='' , blank=True, null=True) 
    resultado = models.CharField(max_length=100, verbose_name='', blank=True, null=True)
    estado = models.CharField(max_length=100, verbose_name='Descripción', blank=True, null=True) 

    def __str__(self):
        fila = 'Nombre: ' + self.nombre
        return fila
    
class HistorialMetrica(models.Model):
    id = models.AutoField(primary_key=True)
    metrica = models.ForeignKey(Metrica, on_delete=models.CASCADE)
    año_historico = models.PositiveIntegerField()
    valor_historico = models.PositiveIntegerField()  # Agrega un valor predeterminado
    mes_historico = models.CharField(max_length=20, verbose_name='Ingrese mes:', choices=MESES, blank=True, null=True)
    año2_historico = models.PositiveIntegerField(blank=True, null=True)
    semestre_historico = models.CharField(max_length=15, verbose_name='Ingrese semestre:', choices=SEMESTRES, blank=True, null=True,)

    def __str__(self):
        if self.mes_historico:
            return str(self.año_historico)+ ' - ' + str(self.mes_historico)
        elif self.semestre_historico:
            return str(self.año_historico)+ ' - ' + str(self.semestre_historico)
        elif self.año2_historico:
            return str(self.año_historico)+ ' - ' + str(self.año2_historico)
        else:
            return str(self.año_historico)

class Ambito(models.Model):
    nombre = models.CharField(max_length=15)
    
    def __str__(self):
        return self.nombre
    
class Tipo(models.Model):
    nombre = models.CharField(max_length=15)
    ambito = models.ForeignKey(Ambito, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre

    
class Programa(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100, 
                              verbose_name='Nombre',
                              unique= True,
                              validators= [
                                  RegexValidator(regex= r'^[a-zA-Z\s]*$',
                                                 message="El nombre no puede contener caracteres especiales.",
                                                 code='invalid_nombre')
                              ])
    descripcion = models.CharField(max_length=50, blank=True, null=True)
    objetivo = models.CharField(max_length=100, blank=True, null=True)
    duracion = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.nombre}"

class Objetivos(models.Model):
    id = models.AutoField(primary_key=True)
    programa = models.PositiveIntegerField()
    nombre = models.CharField(max_length=100, blank=True, null=True)
    
    def __str__(self):
        return self.nombre

class User(AbstractUser):
    email = models.EmailField(unique=True)
    is_owner = models.BooleanField(default=False)
    area = models.CharField(max_length=40, choices=AREAS, blank=True, null=True)
    # frecuencia = models.CharField(max_length=10, choices=FRECUENCIAS)

    # Agrega related_name para evitar el conflicto
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='customuser_set',
        related_query_name='user',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='customuser_set',
        related_query_name='user',
        blank=True,
        help_text='Specific permissions for this user.',
    )

    def __str__(self):
        return self.username

MIRe2/MIReApp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title> {% block titulo %} {% endblock %} </title>
  <link type="text/css" href='{% static "css/base.css" %}' rel="stylesheet"/>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous"> -->
  
  <script src="https://kit.fontawesome.com/3b1b78c3c2.js" crossorigin="anonymous"></script>
</head>

<body style="background-image: url(../../static/images/base.jpg);">
  <nav class="navbar bg-body-tertiary fixed-top" style="background-color: #965FB8; position: fixed;">
    <div class="container-fluid"style="color: #965FB8 !important;">
      <a class="nav-item nav-link fw-bold " style="color: #965FB8 !important;" href="{% url 'inicio' %}" aria-current="page">
      <img src="/../static/images/grafiquita.png" class="rounded-3"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation" >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end rounded-4" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">MIRe UTN</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-item nav-link fw-bold " style="color: #965FB8;" href="{% url 'inicio' %}" aria-current="page">Inicio<span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link fw-bold" style="color: #965FB8;" href="{% url 'programas' %}">Programas</a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link fw-bold" style="color: #965FB8;" href="{% url 'metricas' %}">Métricas</a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link fw-bold" style="color: #965FB8;" href="{% url 'indicadores' %}">Indicadores</a>
            </li>
           
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href={% url 'logout' %}>Salir</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={% url 'editar_perfil' %}>Editar Perfil</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={% url 'perfiles' %}>Perfiles</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href={% url 'login' %}>Ingresar</a>
              </li>        
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href={% url 'registrar_admin' %}>Registrar Administrador</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={% url 'registrar_owner' %}>Registrar Owner</a>
            </li>
          </ul>
          </div>
      </div>
    </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-12" id="formulario-container">
              <br>
              {% block contenido %} {% endblock %}
            </div>
        </div>
        
    </div>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>        
  <!-- Apache ECharts -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.4.1/echarts.min.js"></script>
</body>

</html>

MIRe2/MIReApp/templates/historial_metrica.html
{% extends "base.html" %}

{% block titulo %} Histórico {% endblock %}

{% block contenido %} 
<br>
<br>
<br>
<center>
<div class="card col-md-6" style="text-align: left;">
    <div class="card-header fw-bold" style="background-color: #D7A5FF;color: #000000;">
        <div style="display: flex; justify-content: space-between; align-items: center;">
            <span><a href="{% url 'metricas' %}" class="btn btn-secondary rounded-4 fw-bold" style="background-color: transparent; color: #ffff;border-color: #ffff;border-width: 2px;">⪻ Volver</a></span>
            <span><h2>HISTÓRICO</h2></span>
        </div>
    </div>
    <div class="card-body" >
                <title>Historico de la métrica</title>
                
                <body>
                    <h2>{{ metrica.frecuencia }}</h2>
                    <br>
                    <table class="table rounded-4" style="background-color: #D7A5FF; width: flex;">
                        <tr>
                            {% if metrica.frecuencia == 'Mensual' %}
                                <th>Año</th>
                                <th>Mes</th>
                                <th>Valor</th>
                            {% endif %}
                            {% if metrica.frecuencia == 'Semestral' %}
                                <th>Año</th>
                                <th>Semestre</th>
                                <th>Valor</th>
                            {% endif %}
                            {% if metrica.frecuencia == 'Anual' %}
                                <th>Año</th>                            
                                <th>Valor</th>
                            {% endif %}
                            {% if metrica.frecuencia == 'Bianual' or metrica.frecuencia == 'Cuatrienal'%}
                                <th>Año inicio</th>
                                <th>Año fin</th>
                                <th>Valor</th>
                            {% endif %}                            
                        </tr>

                        {% for item in historial %}
                            <tr>
                                <td scope="row">{{ item.año_historico }}</td>
                                {% if metrica.frecuencia == 'Mensual' %}                              
                                    <td scope="row">{{ item.mes_historico }}</td>
                                {% endif %}
                                {% if metrica.frecuencia == 'Bianual' or metrica.frecuencia == 'Cuatrienal' %} 
                                    <td scope="row">{{ item.año2_historico }}</td>   
                                {% endif %}
                                {% if metrica.frecuencia == 'Semestral' %} 
                                    <td scope="row">{{ item.semestre_historico }}</td>     
                                {% endif %}
                                <td>{{ item.valor_historico }}</td>
                                <td><a class="btn eliminar-btn" data-id="{{ item.id }}" style="background-color: #f60;" role="button"><i class="fa-solid fa-trash-can"></i></a></td>
                            </tr>
                        {% endfor %}                        
                    </table>

                    <br>
                    <h6>Agregar nueva instancia:</h6>
                    <form method="post">
                        {% csrf_token %}
                        <input id="id_year" type="number" name="nuevo_año" required class="rounded-3"  placeholder="Ingrese año" style="border-color: #965FB8;">
                        {% if metrica.frecuencia == 'Mensual' %}
                        <select id="meses" name="nuevo_mes" style="border-color: #965FB8;">
                            <option value="Enero">Enero</option>
                            <option value="Febrero">Febrero</option>
                            <option value="Marzo">Marzo</option>
                            <option value="Abril">Abril</option>
                            <option value="Mayo">Mayo</option>
                            <option value="Junio">Junio</option>
                            <option value="Julio">Julio</option>
                            <option value="Agosto">Agosto</option>
                            <option value="Septiembre">Septiembre</option>
                            <option value="Octubre">Octubre</option>
                            <option value="Noviembre">Noviembre</option>
                            <option value="Diciembre">Diciembre</option>
                        </select>
                        <!-- <input type="string" name="nuevo_mes" required class="rounded-3" placeholder="Ingrese mes" style="border-color: #965FB8;"> -->
                        {% endif %}
                        {% if metrica.frecuencia == 'Semestral' %}                        
                        <select id="semestre" name="nuevo_semestre" style="border-color: #965FB8;">
                            <option value="Enero-Junio">Enero-Junio</option>
                            <option value="Julio-Diciembre">Julio-Diciembre</option>
                        </select>
                            <!-- <input type="number" name="nuevo_semestre" required class="rounded-3" placeholder="Ingrese semenstre" style="border-color: #965FB8;"> -->
                        {% endif %}
                        {% if metrica.frecuencia == 'Bianual' or  metrica.frecuencia == 'Cuatrienal' %}
                            <input id="id_year2" type="number" name="nuevo_año2" readonly value="Este es un campo de solo lectura" required class="rounded-3" placeholder="año fin" style="border-color: #965FB8;">
                        {% endif %}
                        <input type="number" name="nuevo_valor" required class="rounded-3" placeholder="Ingrese valor" style="border-color: #965FB8;">
                        <button type="submit" class="btn rounded-4 fw-bold" style="background-color: #fff4bb;color: #000000;border-color: #ffd500;border-width: 3px;">Agregar</button>
                    </form>
                </body>

                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}

                <script>
                    setTimeout(function() {
                        var altaExitosaMessage = document.querySelector('.messages .alta-exitosa');
                        if (altaExitosaMessage) {
                            altaExitosaMessage.style.display = 'none';
                        }
                    }, 3000);  // Tiempo en el que se muestra el mensaje de éxito
                   
                    var frecuencia = "{{ metrica.frecuencia }}";
                    // frecuencia =   document.getElementById('id_frecuencia')
                    year1 = document.getElementById('id_year')
                    // console.log(year1.value);
                    year1.addEventListener('change', autocompeltarYear2)
                    function autocompeltarYear2(e){
                        if ( frecuencia == 'Bianual' ){
                        year2 = document.getElementById('id_year2')
                        year2.value = parseInt(year1.value) + 1
                        }else if ( frecuencia == 'Cuatrienal' ){
                        console.log('entro');
                        year2 = document.getElementById('id_year2')
                        year2.value = parseInt(year1.value) + 3
                        }
                    }

                </script>

    </div>
    <div class="card-footer text-muted" style="background-color: #D7A5FF;">
        <br>
    </div>   
</div> 
<br> 
</center>
<!-- El siguiente bloque es js-->
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const eliminarButtons = document.querySelectorAll(".eliminar-btn");
        
        eliminarButtons.forEach(button => {
            button.addEventListener("click", function() {
                const historialId = this.getAttribute("data-id");
                
                if (confirm("¿Estás seguro de que deseas eliminar esta instancia?")) {
                    // Realizar la solicitud AJAX para eliminar el historial
                    fetch(`/eliminar_historial_metrica/${historialId}/`, {
                        method: "POST",
                        headers: {
                            "X-CSRFToken": "{{ csrf_token }}",
                            "Content-Type": "application/json"
                        }
                    })
                    .then(response => response.json())
                    .then(data => {
                        // Eliminar la fila de la tabla en la página
                        if (data.success) {
                            const fila = this.closest("tr");
                            fila.remove();
                        }
                    })
                    .catch(error => {
                        console.error("Error:", error);
                    });
                }
            });
        });
    });
</script>


{% endblock %}